import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { Screen, Header, Pill, SectionTitle, styles } from '@/components/Screen';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';
import { router } from 'expo-router';

export default function Today() {
  const colors = useColors(); const { workouts, completedCount } = useApp();
  const next = workouts.find((w) => w.scheduled && !w.completed);
  return <Screen><Header eyebrow="THURSDAY, AUG 20" title="Keep showing up." action={<View style={[local.avatar, { backgroundColor: colors.primary }]}><Text style={{ color: colors.primaryForeground, fontFamily: 'Inter_700Bold' }}>N</Text></View>} />
    <View style={[local.hero, { backgroundColor: colors.card }]}><View><Pill color={colors.accent}>WEEK 01 · FOUNDATION</Pill><Text style={[local.heroTitle, { color: colors.foreground }]}>No perfect days.{'\n'}Just the next one.</Text><Text style={[styles.muted, { color: colors.mutedForeground }]}>Build the habit before you build the miles.</Text></View><View style={local.heroMark}><Feather name="arrow-up-right" size={32} color={colors.primary} /></View></View>
    <View style={local.statRow}><View><Text style={[local.stat, { color: colors.foreground }]}>{completedCount}/7</Text><Text style={[styles.muted, { color: colors.mutedForeground }]}>sessions done</Text></View><View><Text style={[local.stat, { color: colors.foreground }]}>{next ? '06:00' : '—'}</Text><Text style={[styles.muted, { color: colors.mutedForeground }]}>next start</Text></View><View><Text style={[local.stat, { color: colors.foreground }]}>{Math.round((completedCount / 7) * 100)}%</Text><Text style={[styles.muted, { color: colors.mutedForeground }]}>compliance</Text></View></View>
    <SectionTitle>Up next</SectionTitle>
    {next ? <Pressable onPress={() => router.push(next.type === 'rehab' ? '/rehab' : '/run')} style={({ pressed }) => [local.next, { backgroundColor: colors.primary, opacity: pressed ? .82 : 1 }]}><View><Text style={local.nextOverline}>{next.day} · {next.duration}</Text><Text style={local.nextTitle}>{next.title}</Text><Text style={local.nextAction}>Start early <Feather name="arrow-right" size={14} color={colors.primaryForeground} /></Text></View><Feather name="play-circle" size={44} color={colors.primaryForeground} /></Pressable> : <View style={[styles.card, { backgroundColor: colors.card }]}><Text style={[styles.muted, { color: colors.mutedForeground }]}>Your week is complete. Rest is part of the plan.</Text></View>}
    <View style={local.tip}><Feather name="shield" size={18} color={colors.accent} /><Text style={[styles.muted, { color: colors.mutedForeground, flex: 1 }]}>Your tendon readiness score is calculated from consistency, not intensity.</Text></View>
  </Screen>;
}
const local = StyleSheet.create({ avatar: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' }, hero: { borderRadius: 26, padding: 22, minHeight: 220, justifyContent: 'space-between', marginBottom: 18 }, heroTitle: { fontFamily: 'Inter_700Bold', fontSize: 29, lineHeight: 34, letterSpacing: -.8, marginVertical: 18 }, heroMark: { position: 'absolute', right: 20, top: 20 }, statRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 12, marginBottom: 22 }, stat: { fontFamily: 'Inter_700Bold', fontSize: 23 }, next: { minHeight: 130, borderRadius: 22, padding: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 }, nextOverline: { color: '#111315', fontFamily: 'Inter_700Bold', fontSize: 11, letterSpacing: 1 }, nextTitle: { color: '#111315', fontFamily: 'Inter_700Bold', fontSize: 20, marginVertical: 10 }, nextAction: { color: '#111315', fontFamily: 'Inter_600SemiBold', fontSize: 13 }, tip: { flexDirection: 'row', gap: 10, alignItems: 'center', paddingVertical: 14 } });