import React, { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import * as Haptics from 'expo-haptics';
import { Screen, Header, Button, SectionTitle, styles } from '@/components/Screen';
import { useColors } from '@/hooks/useColors';
import { useLocalSearchParams } from 'expo-router';
import { useApp } from '@/context/AppContext';

const exercises = [{ title: 'Soleus Wall Sit Hold', detail: '3 × 45 sec', done: true }, { title: 'Single-Leg Isometric Calf Hold', detail: '3 × 45 sec', done: false }, { title: 'Spanish Squat Isometric Hold', detail: '3 × 30 sec', done: false }];
export default function Rehab() { const colors = useColors(); const { workoutId } = useLocalSearchParams<{ workoutId?: string }>(); const { completeWorkout } = useApp(); const [active, setActive] = useState(1); const [seconds, setSeconds] = useState(45); const [started, setStarted] = useState(false); const [sets, setSets] = useState<number[]>([1]); useEffect(() => { if (!started || seconds === 0) return; const timer = setInterval(() => setSeconds((s) => s - 1), 1000); return () => clearInterval(timer); }, [started, seconds]); useEffect(() => { if (started && seconds === 0) { setStarted(false); setSets((s) => [...s, s.length + 1]); Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); } }, [seconds, started]);
  return <Screen><Header eyebrow="JOINT PREP" title="Rehab player" /><View style={[local.progress, { backgroundColor: colors.card }]}><View style={[local.progressFill, { backgroundColor: colors.accent, width: '36%' }]} /><Text style={[styles.muted, { color: colors.mutedForeground, marginTop: 10 }]}>1 of 3 exercises complete</Text></View><SectionTitle>Today's routine</SectionTitle>{exercises.map((item, i) => <Pressable key={item.title} onPress={() => !item.done && setActive(i)} style={[local.exercise, { backgroundColor: active === i ? colors.secondary : colors.card }]}><View style={[local.check, { borderColor: item.done ? colors.accent : colors.border, backgroundColor: item.done ? colors.accent : 'transparent' }]}>{item.done && <Text style={{ color: colors.background, fontFamily: 'Inter_700Bold' }}>✓</Text>}</View><View style={{ flex: 1 }}><Text style={[local.exerciseTitle, { color: colors.foreground }]}>{item.title}</Text><Text style={[styles.muted, { color: colors.mutedForeground }]}>{item.detail}</Text></View><Text style={[local.status, { color: item.done ? colors.accent : active === i ? colors.primary : colors.mutedForeground }]}>{item.done ? 'DONE' : active === i ? 'START' : 'LOCKED'}</Text></Pressable>)}<View style={[local.player, { backgroundColor: colors.card }]}><Text style={[local.playerEyebrow, { color: colors.primary }]}>EXERCISE {active + 1} · ISOMETRIC</Text><Text style={[local.playerTitle, { color: colors.foreground }]}>{exercises[active].title}</Text><Text style={[styles.muted, { color: colors.mutedForeground }]}>Place the ball of your foot on a step. Drive your heel up and hold a neutral ankle position.</Text><View style={[local.timer, { borderColor: started ? colors.primary : colors.border }]}><Text style={[local.timerText, { color: colors.foreground }]}>00:{seconds.toString().padStart(2, '0')}</Text><Text style={[styles.muted, { color: colors.mutedForeground }]}>SET {sets.length} OF 3</Text></View><Button label={started ? 'Pause timer' : 'Start 45 sec timer'} icon={started ? 'pause' : 'play'} secondary={started} onPress={() => { if (seconds === 0) setSeconds(45); setStarted(!started); }} /></View><Button label="Complete workout" icon="check-circle" onPress={() => { if (workoutId) completeWorkout(workoutId); Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); }} /></Screen> }
const local = StyleSheet.create({ progress: { borderRadius: 18, padding: 16, marginBottom: 20 }, progressFill: { height: 7, borderRadius: 5 }, exercise: { flexDirection: 'row', alignItems: 'center', gap: 12, borderRadius: 17, padding: 14, marginBottom: 8 }, check: { width: 26, height: 26, borderRadius: 13, borderWidth: 2, alignItems: 'center', justifyContent: 'center' }, exerciseTitle: { fontFamily: 'Inter_700Bold', fontSize: 14, marginBottom: 3 }, status: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: .8 }, player: { borderRadius: 22, padding: 19, marginTop: 18, marginBottom: 16 }, playerEyebrow: { fontFamily: 'Inter_700Bold', letterSpacing: 1.3, fontSize: 10 }, playerTitle: { fontFamily: 'Inter_700Bold', fontSize: 22, marginVertical: 10 }, timer: { width: 150, height: 150, borderRadius: 75, borderWidth: 5, alignSelf: 'center', marginVertical: 20, alignItems: 'center', justifyContent: 'center' }, timerText: { fontFamily: 'Inter_700Bold', fontSize: 34, letterSpacing: -1 }, });