import React, { useEffect, useState } from 'react';
import { Alert, StyleSheet, Text, View } from 'react-native';
import * as Location from 'expo-location';
import * as Haptics from 'expo-haptics';
import { Screen, Header, Button, Pill, SectionTitle } from '@/components/Screen';
import { useColors } from '@/hooks/useColors';

export default function Run() { const colors = useColors(); const [running, setRunning] = useState(false); const [seconds, setSeconds] = useState(0); const [permission, setPermission] = useState(false);
  useEffect(() => { if (!running) return; const timer = setInterval(() => setSeconds((s) => s + 1), 1000); return () => clearInterval(timer); }, [running]);
  const start = async () => { const result = await Location.requestForegroundPermissionsAsync(); if (result.status !== 'granted') { Alert.alert('Location needed', 'Allow location access to render your live route and calculate pace.'); return; } setPermission(true); setRunning(true); Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium); };
  const finish = () => { setRunning(false); Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success); Alert.alert('Walk logged', 'Nice work. Your session has been saved locally.'); };
  const mins = Math.floor(seconds / 60).toString().padStart(2, '0'); const secs = (seconds % 60).toString().padStart(2, '0');
  return <Screen scroll={false}><Header eyebrow="OUTDOOR SESSION" title="Run tracking" action={<Pill color={colors.secondary}>{permission ? 'GPS READY' : 'GPS OFF'}</Pill>} /><View style={[local.metricHero, { backgroundColor: colors.card }]}><Text style={[local.metricLabel, { color: colors.mutedForeground }]}>DISTANCE REMAINING</Text><Text style={[local.distance, { color: colors.foreground }]}>{running ? '1.85' : '2.50'} <Text style={local.unit}>MI</Text></Text><View style={local.metrics}><View><Text style={[local.metricValue, { color: colors.foreground }]}>{running ? `0${mins}:${secs}` : '00:00'}</Text><Text style={[local.metricLabel, { color: colors.mutedForeground }]}>TIME</Text></View><View><Text style={[local.metricValue, { color: colors.foreground }]}>{running ? `9'45"` : `10'00"`}</Text><Text style={[local.metricLabel, { color: colors.mutedForeground }]}>PACE / MI</Text></View><View><Text style={[local.metricValue, { color: colors.foreground }]}>135</Text><Text style={[local.metricLabel, { color: colors.mutedForeground }]}>BPM</Text></View></View></View><View style={[local.map, { backgroundColor: colors.secondary }]}><View style={local.mapGrid}><View style={[local.route, { borderColor: colors.primary }]} /><View style={[local.dot, { backgroundColor: colors.primary }]} /></View><Text style={[local.mapLabel, { color: colors.mutedForeground }]}>{running ? 'LIVE GPS MAP' : 'ROUTE PREVIEW'}</Text></View><SectionTitle>Keep your pace easy</SectionTitle><Text style={[local.copy, { color: colors.mutedForeground }]}>The goal today is to leave enough in the tank to come back tomorrow.</Text><View style={local.controls}>{running ? <Button label="Finish session" icon="square" onPress={finish} /> : <Button label="Start outdoor session" icon="play" onPress={start} />}</View></Screen> }
const local = StyleSheet.create({ metricHero: { borderRadius: 24, padding: 20, marginBottom: 12 }, metricLabel: { fontFamily: 'Inter_700Bold', letterSpacing: 1.1, fontSize: 10 }, distance: { fontFamily: 'Inter_700Bold', fontSize: 56, letterSpacing: -2, marginVertical: 8 }, unit: { fontSize: 18, letterSpacing: 0 }, metrics: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#303738', paddingTop: 18, marginTop: 4 }, metricValue: { fontFamily: 'Inter_700Bold', fontSize: 20, marginBottom: 4 }, map: { height: 180, borderRadius: 24, overflow: 'hidden', justifyContent: 'center', alignItems: 'center', marginBottom: 18 }, mapGrid: { width: '85%', height: '70%', borderWidth: 1, borderColor: '#3A4544', borderRadius: 20, position: 'relative', transform: [{ rotate: '-8deg' }] }, route: { position: 'absolute', width: '70%', height: '90%', borderWidth: 4, borderLeftColor: 'transparent', borderBottomColor: 'transparent', borderRadius: 80, top: 6, left: 28 }, dot: { width: 13, height: 13, borderRadius: 7, position: 'absolute', right: 28, bottom: 10 }, mapLabel: { position: 'absolute', bottom: 15, fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1 }, copy: { fontFamily: 'Inter_400Regular', fontSize: 14, lineHeight: 20 }, controls: { marginTop: 'auto' as unknown as number, paddingTop: 20 } });