import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Screen, Header, Button, Pill, SectionTitle, styles } from '@/components/Screen';
import { useApp, Workout } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';
import { Feather } from '@expo/vector-icons';

function WorkoutRow({ item }: { item: Workout }) { const colors = useColors(); const { toggleSchedule } = useApp(); return <View style={[local.row, { backgroundColor: colors.card }]}><View style={[local.day, { backgroundColor: item.scheduled ? colors.primary : colors.secondary }]}><Text style={{ color: item.scheduled ? colors.primaryForeground : colors.mutedForeground, fontFamily: 'Inter_700Bold', fontSize: 11 }}>{item.day}</Text></View><View style={{ flex: 1 }}><Text style={[local.rowTitle, { color: colors.foreground }]}>{item.title}</Text><Text style={[styles.muted, { color: colors.mutedForeground }]}>{item.duration} · {item.type === 'rehab' ? 'joint prep' : item.type === 'run' ? 'outdoors' : 'easy pace'}</Text></View>{item.completed ? <Pill color={colors.accent}>DONE</Pill> : <Button label={item.scheduled ? 'Booked' : 'Schedule'} secondary={!item.scheduled} onPress={() => toggleSchedule(item.id)} />}</View> }
export default function Schedule() { const colors = useColors(); const { workouts, scheduleAll } = useApp(); return <Screen><Header eyebrow="YOUR WEEK" title="Schedule" action={<Feather name="bell" size={22} color={colors.foreground} />} /><View style={[local.notice, { backgroundColor: colors.card }]}><Feather name="clock" size={20} color={colors.primary} /><View style={{ flex: 1 }}><Text style={[local.noticeTitle, { color: colors.foreground }]}>T−15 reminders</Text><Text style={[styles.muted, { color: colors.mutedForeground }]}>Set your routine once. We’ll keep the next session visible.</Text></View></View><Button label="Multi-schedule all 7 days" icon="calendar" onPress={scheduleAll} /><Text style={[styles.muted, { color: colors.mutedForeground, marginVertical: 18 }]}>A gentle first week designed to condition your body before you chase pace.</Text><SectionTitle>Initial 1-week plan</SectionTitle>{workouts.map((item) => <WorkoutRow key={item.id} item={item} />)}</Screen> }
const local = StyleSheet.create({ notice: { flexDirection: 'row', gap: 12, padding: 17, borderRadius: 18, marginBottom: 16 }, noticeTitle: { fontFamily: 'Inter_700Bold', fontSize: 15, marginBottom: 4 }, row: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 12, borderRadius: 18, marginBottom: 9 }, day: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, rowTitle: { fontFamily: 'Inter_700Bold', fontSize: 14, marginBottom: 3 } });